[package]
name = "lilliput-core"
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
version = "0.1.0"

[dependencies]
num-traits = { version = "0.2.19", default-features = false }
ordermap = { version = "0.5.5", optional = true }
thiserror = "2.0.12"

[features]
preserve_order = [
    "ordermap"
]

