[package]
name = "lilliput-core"
license = { workspace = true }
version = "0.1.0"
edition = "2024"

[dependencies]
ordermap = { version = "0.5.5", optional = true }
thiserror = "2.0.12"

[features]
preserve_order = [
    "ordermap"
]

