[package]
name = "lilliput-core"
license = { workspace = true }
version = "0.1.0"
edition = "2024"

[dependencies]
decorum = "0.4.0"
num-traits = { version = "0.2.19", default-features = false }
ordermap = { version = "0.5.5", optional = true }
thiserror = "2.0.12"

[dev-dependencies]
proptest = "1.6.0"
proptest-derive = "0.5.1"

[features]
preserve_order = [
    "ordermap"
]

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3
